### PR TITLE
Update structurerandom.m

### PR DESCRIPTION
**Pull request by MARIACONCETTA**
I don't know if i've used coorrectly the program

### CODE REVIEW

**Comment by hprasetya** [comment]
It would help to understand the update if you explain briefly what changes you made and why.

**Comment by MARIACONCETTA** [comment]
ok,you have said that matlab  take vessel 4 to generate vessels in perfusionarea 5.05, i put "if not egual to 4 "inside "for cycle" for nie to eliminate the element generated from vessel 4 and only to understand if there would have been other overlaps....and i've discovered that yes there are , so i have understood that the problem it's not only for vessel 4 but also for other vessels expecially that one that have few number of positions in distancematrix. Have you suggest to solve it?  I think that I need to change the definition of numberofposition, the suspicion is correct?

**Comment by hprasetya** [comment]
I don't think the problem simply in the vessel 4 in particular, because it's generated by a loop with the same rule & condition for each iteration. Unless vessel 4 has different characteristic compared to others (like vessel 5 which only has one side of perfusion area), removing vessel 4 wouldn't unravel the overlapping. My suggestion would be to look at the incremental value which indicates target vessel (counterie and/or nie). See if those variable increasing at the usual pace around "i+nse=5". My guess there would be a hiccup in the increment during that specific iteration, making vessel 4 as a root vessel for perfusion area 5.05 instead of vessel 5.

**Comment by hprasetya** [comment]
I'll close this thread now. Please make a new pull request when you make further change.

**Pull request closed without merging**
